{
 "title": "Destiny 2 Player Statistics Example",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "character",
    "label": "character",
    "query": "label_values(d2_kills_with,character)"
   },
   {
    "name": "weapon",
    "label": "weapon",
    "query": "label_values(d2_kills_with,weapon)"
   },
   {
    "name": "activity",
    "label": "activity",
    "query": "label_values(d2_kills_with,activity_type)"
   }
  ]
 },
 "panels": [
  { "title": "Historical Data", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "% of time played as $character in $activity",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short", "label": "% of time" }
   ],
   "targets": [
    {
     "expr": "(d2_seconds_played{activity_type=~\"$activity\", character=~\"$character\"} / ignoring (character) group_left d2_seconds_played{activity_type=~\"$activity\", character=\"merged\"}) * 100",
     "legendFormat": "{{character}}: {{activity_type}}"
    }
   ]
  },
  {
   "title": "% of all kills as $character in $activity",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short", "label": "% of kills" }
   ],
   "targets": [
    {
     "expr": "(d2_total_kills{activity_type=~\"$activity\", character=~\"$character\"} / ignoring (character) group_left d2_total_kills{activity_type=~\"$activity\", character=\"merged\"}) * 100",
     "legendFormat": "{{character}}: {{activity_type}}"
    }
   ]
  },
  { "title": "Instant Data", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Activity Clear Rate",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "round((d2_activities_cleared / d2_activities_entered) * 100)",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "Kills: $activity",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "d2_total_kills{activity_type=~\"$activity\", character=~\"$character\"}",
     "legendFormat": "{{character}}"
    }
   ]
  },
  {
   "title": "Precision Kills: $activity",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "d2_precision_kills{activity_type=~\"$activity\", character=~\"$character\"}",
     "legendFormat": "{{character}}"
    }
   ]
  },
  {
   "title": "Deaths: $activity",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "d2_total_deaths{activity_type=~\"$activity\", character=~\"$character\"}",
     "legendFormat": "{{character}}"
    }
   ]
  },
  {
   "title": "Suicides: $activity",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "d2_suicides{activity_type=~\"$activity\", character=~\"$character\"}",
     "legendFormat": "{{character}}"
    }
   ]
  },
  {
   "title": "Ressurections Performed: $activity",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "d2_resurrections{activity_type=~\"$activity\", character=~\"$character\", action=\"performed\"}",
     "legendFormat": "{{character}}"
    }
   ]
  },
  {
   "title": "Ressurections Received: $activity",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "d2_resurrections{activity_type=~\"$activity\", character=~\"$character\", action=\"received\"}",
     "legendFormat": "{{character}}"
    }
   ]
  },
  {
   "title": "Orbs Dropped: $activity",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "d2_orbs{activity_type=~\"$activity\", character=~\"$character\", action=\"dropped\"}",
     "legendFormat": "{{character}}"
    }
   ]
  },
  {
   "title": "Orbs Gathered: $activity",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "d2_orbs{activity_type=~\"$activity\", character=~\"$character\", action=\"gathered\"}",
     "legendFormat": "{{character}}"
    }
   ]
  },
  {
   "title": "K/D Ratio: $activity",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "d2_kd{activity_type=~\"$activity\", character=~\"$character\"}",
     "legendFormat": "{{character}}"
    }
   ]
  },
  {
   "title": "K/D/A Ratio: $activity",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "d2_kda{activity_type=~\"$activity\", character=~\"$character\"}",
     "legendFormat": "{{character}}"
    }
   ]
  },
  {
   "title": "Kills With $weapon in $activity for $character",
   "type": "bargauge",
   "description": "Shows the trend of kills by weapon over time",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "d2_kills_with{character=~\"$character\", weapon=~\"$weapon\", activity_type=~\"$activity\"}",
     "legendFormat": "{{weapon}}"
    }
   ]
  }
 ]
}